# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5rsKkr88YLXy7BNcVvdVOvn6cgakGBu
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("📊 Student Performance Analyzer")

uploaded_file = st.file_uploader("Upload Student CSV File", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.subheader("📄 Student Data")
    st.dataframe(df)

    st.subheader("📈 Statistics")
    st.write(df.describe())

    st.subheader("🎯 Filter Students by Total Marks")
    min_marks = st.slider("Select minimum total marks", 0, 300, 150)

    filtered_df = df[df["Total"] >= min_marks]
    st.dataframe(filtered_df)

    st.subheader("📊 Total Marks Chart")
    fig, ax = plt.subplots()
    ax.bar(filtered_df["Name"], filtered_df["Total"])
    ax.set_xlabel("Student Name")
    ax.set_ylabel("Total Marks")
    ax.set_title("Student Total Marks")

    st.pyplot(fig)
else:
    st.info("👆 Upload a CSV file to get started")